language: java
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

env:
  global:
  - ZOOKEEPER_PEERS=localhost:2181
  - KAFKA_PEERS=localhost:9092

before_install:
- wget http://www.us.apache.org/dist/kafka/0.10.2.0/kafka_2.11-0.10.2.0.tgz -O kafka.tgz
- mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
- nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
- sleep 10
- nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
- sleep 20

before_script:
- psql -U postgres -c 'CREATE DATABASE citizens;'
- psql -U postgres -d citizens -a -f ./postgres/citizensNew.sql
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
- sleep 50
- mvn test
